### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by roma-kolomiiets** [roma-kolomiiets/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by not-roma-kolomiiets** [comment]
A sponge with over 7 years of dedicated service to the Krusty Krab and 5 years of Jellyfish fishing. Posesses unadulterated enthusiasm for his work and passion in reaching his goals.
