### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by roma-kolomiiets** [roma-kolomiiets/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by not-roma-kolomiiets** [comment]
https://uk-ua.facebook.com/spongebob
spongebob@bikinibottom.com 
https://twitter.com/spongebob
https://www.instagram.com/spongebob/?hl=ru
