### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by roma-kolomiiets** [roma-kolomiiets/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by not-roma-kolomiiets** [comment]
EXPERIENCE
Aug. 2013 – Present
Krusty Krab
 Head Chef
Prepped food for 60-seat restaurant, with ability to accurately cut ingredients according to specifications 20% faster than Squidward, as well as prepare stocks and long cook items
Trained new cook Patrick Star, who had no prior experience in fast food
Ensured supplies were consistently available, replenishing items as required in aid of cooks, regularly receiving commendation from Mr. Krabs for organizational skills
Memorized the Krusty Krab recipe quickly, and dutifully guarded its contents from Plankton
Oct. 2011 – Aug. 2013
Oshin Institute Division of Housing and Food Services
Food-Prep
Prepared meals at dormitory cafeteria
Manage and supervise other employees during closing
Jun. 2006 – Aug. 2011
Jelly Jellies Camp
Head Jelly Counselor and Fun Coach
F is for friends who do stuff together
U is for you and me
N is for anywhere and anytime at all
Instructed and taught kids the fundamentals of Jellyfish fishing while maintaining a positive environment 
EDUCATION & CERTIFICATIONS
April 2009
 Program Graduate Mr. Krabs Workforce Development Training
May 2004 
Commercial Boating License Mrs. Puff’s Boating School
May 2001 
High School Diploma South Sea High School
