### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by roma-kolomiiets** [roma-kolomiiets/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by not-roma-kolomiiets** [comment]
ORGANIZATIONS/CLUBS
Sigma Phi Nu Gamma Fraternity
University Jellyfishing Club
University Karate Club
Club SpongeBob
CORE QUALIFICATIONS
Teamwork
Responsibility
Well organized 
Communication
Integrity
LANGUAGES
en ENGLISH ua Ukraininan
SKILLS/HONORS/AWARDS
Triple rainbow belt in Karate
Defending champion left-handed thumb wrestling
Defending champion right-handed thumb wrestling
Annoying Squidward
Proficient skills in bubble blowing
LIFE CREDO
If you believe in yourself and with a tiny pinch of magic, all your dreams can come true

LIKES 
Job as a fry cook and spending time with best friends, especially when they’re jellyfishing or practicing their kah-rah-tay.
DISLIKES 
 Days off, the dark, clowns.
